services:
  mikroutils:
    build:
      target: production
    ports:
      - "80:80"
    extends:
      file: compose-base.yml
      service: mikroutils
    networks:
      - dokploy-network

networks:
  dokploy-network:
    external: true