services:
  app:
    build:
      target: production
    ports:
      - "3535:80"
    volumes:
      - ./:/var/www/html/
    environment:
      APP_UID: "1000"
      APP_GID: "1000"
    extra_hosts:
      - host.docker.internal:host-gateway
    extends:
      file: compose-base.yml
      service: app
    networks:
      - dokploy-network
  database:
    image: postgres:16-alpine
    environment: 
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}" 
    ports:
      - "5442"
    networks:
      - dokploy-network
    volumes:
      - database_data:/var/lib/postgresql/data:rw
volumes:
  database_data:

networks:
  dokploy-network:
    external: true