services:
  app:
    build:
      target: production
    ports:
      - "80:80"
    extends:
      file: compose-base.yml
      service: app
    networks:
      - dokploy-network
  database:
    image: postgres:16-alpine
    ports:
      - "5442"
    env_file: .env.prod.local
    volumes:
      - database_data:/var/lib/postgresql/data:rw

volumes:
  database_data:

networks:
  dokploy-network:
    external: true